# Netlify Configuration for Student Portfolio
# This connects your GitHub repository to Netlify for auto-deployment

# Build settings
[build]
  # No build command needed for static site
  publish = "."
  
# GitHub integration - automatic deployment
[build.environment]
  # This ensures Netlify pulls from your GitHub repo
  NODE_VERSION = "18"
  # CRITICAL: Disable Netlify Identity completely
  NETLIFY_IDENTITY_ENABLED = "false"

# OVERRIDE all Netlify Identity redirects - FORCE our custom admin
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/admin-login.html"
  status = 301
  force = true

[[redirects]]
  from = "/admin/accept-invite*"
  to = "/admin-login.html"
  status = 301
  force = true

[[redirects]]
  from = "/admin/login*"
  to = "/admin-login.html" 
  status = 301
  force = true

# Our custom admin system
[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-panel"
  to = "/admin.html"
  status = 200

# Catch all admin routes to our custom login
[[redirects]]
  from = "/admin/*"
  to = "/admin-login.html"
  status = 200

# Error page handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Protect admin files from search engines
[[headers]]
  for = "/admin*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/admin*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
